### ISSUE TITLE
The information of 87s is not showing correctly

### ISSUE THREAD

**Issue by qwqtoday** [angus6b23/hk-transport#3]
Information for both destination should be different, if I check 87s at morning it does not show the time correctly

**Comment by angus6b23** [comment]
The app's data is currently align with the official page of kmb as I checked. The destination and origin may be same in some circular lines.
![圖片](https://github.com/angus6b23/hk-transport/assets/15632591/4586405d-d7df-456a-a991-c916d45e8165)
![圖片](https://github.com/angus6b23/hk-transport/assets/15632591/4083b6f0-0244-4d53-96bc-ef397253ad2a)
![圖片](https://github.com/angus6b23/hk-transport/assets/15632591/ab00b55f-42bb-4882-899a-e914699eb627)
![圖片](https://github.com/angus6b23/hk-transport/assets/15632591/015e200c-33e4-4c55-9131-3a677f8955af)

**Comment by qwqtoday** [comment]
![螢幕擷取畫面 2023-12-12 065621](https://github.com/angus6b23/hk-transport/assets/77849373/5e91375c-5f2a-42bb-8e43-ae495b14ed2d)
![螢幕擷取畫面 2023-12-12 065439](https://github.com/angus6b23/hk-transport/assets/77849373/2d7bab4e-0c31-4d1c-b100-3a035bcdeebd)
![螢幕擷取畫面 2023-12-12 065518](https://github.com/angus6b23/hk-transport/assets/77849373/9b17637a-6df2-48e9-9785-0531b1f198ea)
![螢幕擷取畫面 2023-12-12 065540](https://github.com/angus6b23/hk-transport/assets/77849373/b0a7e9b8-d456-4e47-a7aa-56e1263d56b7)

**Comment by qwqtoday** [comment]
It’s 8 AM at the morning and it doesn’t show the next bus time for me, that’s my main issue ![IMG_1636](https://github.com/angus6b23/hk-transport/assets/77849373/9e57da2a-722f-4e2f-a6e6-95ef5076aca4)
![IMG_1635](https://github.com/angus6b23/hk-transport/assets/77849373/75522119-fdf8-4331-9cf1-2614843e2cda)

**Comment by angus6b23** [comment]
Thanks for the clarification. The problems seems to be the scraper from the backend and I have made a temporary workaround for 87S. Update the route data in option of the app and it suppose to work.

**Comment by qwqtoday** [comment]
Both destination time aren't correct, it is not fixed

![image](https://github.com/angus6b23/hk-transport/assets/77849373/3350a464-8d86-46b4-93a9-b3b13707343b)![image](https://github.com/angus6b23/hk-transport/assets/77849373/61f7d553-4a57-497c-ae58-43d7a82a66f9)
![image](https://github.com/angus6b23/hk-transport/assets/77849373/de0a1954-93f8-47a4-94a6-aee8930e3c47)
![image](https://github.com/angus6b23/hk-transport/assets/77849373/3c08c791-f511-4365-af57-e789fe02db0a)

**Comment by angus6b23** [comment]
I have moved the issue to the backend repo. Please see:
https://github.com/angus6b23/hk-transport-backend/issues/1
