### ISSUE TITLE
Back button cannot be used to exit the app

### ISSUE THREAD

**Issue by Crissium** [angus6b23/hk-transport#5]
Hello and thanks for the wonderful app!

There is one tiny problem that might negatively impact user experience: pressing the back button brings the user back to the previous screen, but when the user navigates back to the home screen, pressing the button again does not exit the app. I think normally the back button could be used to quit the app, so it would be marvellous if this functionality is added. Thanks again!

The version I am using is the latest on F-Droid, namely v1.0.5.

**Comment by angus6b23** [comment]
Thank you for your suggestion. I will implement the feature in the next release
